# Generated by Django 3.2.7 on 2021-10-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nickname',
            field=models.CharField(default='익명', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
