# Generated by Django 3.2.7 on 2021-10-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211005_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nickname',
            field=models.CharField(default=models.CharField(default='Anonymous', max_length=20), max_length=20),
        ),
    ]
